[package]
name = "asi-camera-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cross = "0.2.5"
libc = "0.2"

[build-dependencies]

bindgen = "0.65.1"

